name:                BOT-Haskell
version:             0.1.0.0
github:              "githubuser/BOT-Haskell"
license:             BSD3
author:              "Homarechan"
maintainer:          "tikuwakunn@icloud.com"
copyright:           "2019 Homarechan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Homarechan/BOT-Haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - bytestring
    - containers
    - ghc-prim
    - attoparsec
    - binary
    - bytestring >= 0.10
    - base64-bytestring
    - hashable
    - HTTP
    - text
    - hspec-core > 2.4.0
    - unordered-containers >= 0.2.6
    - vector >= 0.10.12.2
    - QuickCheck >= 2.8.2
    - split
    - network-uri >= 2.6
    - network >= 2.6.0.2

executables:
  BOT-Haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BOT-Haskell
    - bytestring
    - containers
    - ghc-prim
    - attoparsec
    - binary
    - bytestring >= 0.10
    - base64-bytestring
    - hashable
    - HTTP
    - text
    - hspec-core > 2.4.0
    - unordered-containers >= 0.2.6
    - vector >= 0.10.12.2
    - QuickCheck >= 2.8.2
    - split
    - network-uri >= 2.6
    - network >= 2.6.0.2

tests:
  BOT-Haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BOT-Haskell
    - bytestring
    - containers
    - ghc-prim
    - attoparsec
    - binary
    - bytestring >= 0.10
    - base64-bytestring
    - hashable
    - HTTP
    - text
    - hspec-core > 2.4.0
    - unordered-containers >= 0.2.6
    - vector >= 0.10.12.2
    - QuickCheck >= 2.8.2
    - split
    - network-uri >= 2.6
    - network <= 2.6.0.2
